/**
 * Generated by scripts/build-corpus.py. Do not edit — rebuild the corpus.
 *
 * The app needs a few facts about the corpus before it can draw anything, and
 * fetching them would put a round trip in front of the first poem. They are
 * facts about a corpus that changes only when the corpus does, so they are
 * compiled in, and `CORPUS_BUILD` is the stamp the artifacts carry: a hash of
 * every column, every dictionary and the text of every chunk (also in
 * facets.json.gz, which is where a mismatch is worth noticing; the search index
 * records the same stamp in search/meta.json, because an index built from
 * another corpus answers without saying so).
 *
 * `CORPUS_ORDER` is the axis order of a chunk's positional labels. The app
 * reads its positions out of this list by name rather than by number, so
 * reordering the axes here cannot silently print one label where another
 * belongs.
 */
export const CORPUS_N = 125314
export const CORPUS_PER_CHUNK = 20
export const CORPUS_CHUNKS = 6266
export const CORPUS_BUILD = '3ade8e64'
export const CORPUS_ORDER = ['coll', 'cat', 'juan', 'chapter', 'era', 'author', 'form', 'len', 'lang', 'olang', 'mood', 'view'] as const

/** Every axis the corpus stores, in the order a chunk's labels are written. */
export type CorpusAxis = (typeof CORPUS_ORDER)[number]
